name: Workflow testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: Show directory before check out
        run: ls -l
      - uses: actions/checkout@v2
      - name: Show directory after check out
        run: ls -l

   
